### ISSUE TITLE
Project built using Blueprint cannot function as standalone python applications 

### ISSUE THREAD

**Issue by nsenno-dbr** [databrickslabs/blueprint#46]
When attempting to run the Python API of a project built using Blueprint, there is an error associated when initializing the logger. Specifically, it is unable to find the project root. 

Python applications extending the blueprint library should be able to run without explicitly having a project root.  Note this is run on `databricks-labs-remorph==0.2.1` with `databricks-labs-blueprint==0.1.0` 

![image](https://github.com/databrickslabs/blueprint/assets/59416974/63d792e5-144c-47e3-a692-b9ac5eba84be)

**Comment by nsenno-dbr** [comment]
This issue may be solved by https://github.com/databrickslabs/blueprint/pull/43

**Comment by nfx** [comment]
Use logging.getLogger(__name__) for non-installer files
